PROCESS BEFORE OUTPUT.
 MODULE status_0100.
  CALL SUBSCREEN sub1 INCLUDING sy-repid '0101'.
  CALL SUBSCREEN sub2 INCLUDING sy-repid '0102'.
  CALL SUBSCREEN sub3 INCLUDING sy-repid '0103'.
  CALL SUBSCREEN sub4 INCLUDING sy-repid '0104'.
  CALL SUBSCREEN sub5 INCLUDING sy-repid '0105'.
  CALL SUBSCREEN sub6 INCLUDING sy-repid '0106'.
  CALL SUBSCREEN sub7 INCLUDING sy-repid '0107'.


PROCESS AFTER INPUT.
  CALL SUBSCREEN sub1.
  CALL SUBSCREEN sub2.
  CALL SUBSCREEN sub3.
  CALL SUBSCREEN sub4.
  CALL SUBSCREEN sub5.
  CALL SUBSCREEN sub6.
  CALL SUBSCREEN sub7.
  MODULE user_command_0100.