PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'KITAPLISTE'
  MODULE KITAPLISTE_INIT.
*&SPWIZARD: MODULE KITAPLISTE_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE KITAPLISTE_CHANGE_COL_ATTR.
  LOOP AT   G_KITAPLISTE_ITAB
       INTO G_KITAPLISTE_WA
       WITH CONTROL KITAPLISTE
       CURSOR KITAPLISTE-CURRENT_LINE.
*&SPWIZARD:   MODULE KITAPLISTE_CHANGE_FIELD_ATTR
    MODULE KITAPLISTE_MOVE.
    MODULE KITAPLISTE_GET_LINES.
  ENDLOOP.

* MODULE STATUS_0104.
PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0104.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'KITAPLISTE'
  LOOP AT G_KITAPLISTE_ITAB.
    CHAIN.
      FIELD ZKITAPBILGI-KOD.
      FIELD ZKITAPBILGI-AD.
      FIELD ZKITAPBILGI-SAYFA.
      FIELD ZKITAPBILGI-TUR.
      FIELD ZKITAPBILGI-YAZAR.
      FIELD ZKITAPBILGI-BASIMTARIHI.
      FIELD ZKITAPBILGI-STOK.
    ENDCHAIN.
  ENDLOOP.
  MODULE KITAPLISTE_USER_COMMAND.
*&SPWIZARD: MODULE KITAPLISTE_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE KITAPLISTE_CHANGE_COL_ATTR.