PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'KULLANICIBILGI'
  MODULE KULLANICIBILGI_INIT.
*&SPWIZARD: MODULE KULLANICIBILGI_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE KULLANICIBILGI_CHANGE_COL_ATTR.
  LOOP AT   G_KULLANICIBILGI_ITAB
       INTO G_KULLANICIBILGI_WA
       WITH CONTROL KULLANICIBILGI
       CURSOR KULLANICIBILGI-CURRENT_LINE.
*&SPWIZARD:   MODULE KULLANICIBILGI_CHANGE_FIELD_ATTR
    MODULE KULLANICIBILGI_MOVE.
  ENDLOOP.

* MODULE STATUS_0105.

PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'KULLANICIBILGI'
  LOOP AT G_KULLANICIBILGI_ITAB.
    CHAIN.
      FIELD ZKULLANICIBILGI-KULLANICIID.
      FIELD ZKULLANICIBILGI-KULLANICIAD.
      FIELD ZKULLANICIBILGI-KULLANICISOYAD.
      FIELD ZKULLANICIBILGI-KULLANICIYAS.
      FIELD ZKULLANICIBILGI-KULLANICITELEFON.
      FIELD ZKULLANICIBILGI-KULLANICIMAIL.
      FIELD ZKULLANICIBILGI-KULLANICICINSIYET.
    ENDCHAIN.
  ENDLOOP.
*&SPWIZARD: MODULE KULLANICIBILGI_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE KULLANICIBILGI_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0105.