PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'KITAPODUNC'
  MODULE KITAPODUNC_INIT.
*&SPWIZARD: MODULE KITAPODUNC_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE KITAPODUNC_CHANGE_COL_ATTR.
  LOOP AT   G_KITAPODUNC_ITAB
       INTO G_KITAPODUNC_WA
       WITH CONTROL KITAPODUNC
       CURSOR KITAPODUNC-CURRENT_LINE.
*&SPWIZARD:   MODULE KITAPODUNC_CHANGE_FIELD_ATTR
    MODULE KITAPODUNC_MOVE.
  ENDLOOP.

 MODULE STATUS_0107.
*
PROCESS AFTER INPUT.

*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'KITAPODUNC'
  LOOP AT G_KITAPODUNC_ITAB.
    CHAIN.
      FIELD ZKITAPODUNC-ODUNC_TARIHI.
      FIELD ZKITAPODUNC-TESLIM_TARIHI.
      FIELD ZKITAPODUNC-KITAPAD.
      FIELD ZKITAPODUNC-KULLANICIISIM.
      FIELD ZKITAPODUNC-KULLANICISOYISIM.
    ENDCHAIN.
  ENDLOOP.
*&SPWIZARD: MODULE KITAPODUNC_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE KITAPODUNC_CHANGE_COL_ATTR.


 MODULE USER_COMMAND_0107.